### ISSUE TITLE
MongoDB not responding after several hours: 504 Gateway Time-out error

### ISSUE THREAD

**Issue by jeffokamoto** [thesteve0/fluentwebmap#2]
Hi,

I have signed up for a free OpenShift account and was able to successfully bring up my own copy of this application.  However, after several hours, the DB no longer is accessible: the URL /ws/parks (which should return all the parks in JSON format) returns a 504 Gateway Time-out error.  If I restart the webapp via the OpenShift console, then it all starts working again.  (I've left my webapp in the broken state -- if you want to debug it, I can send you my OpenShift domain).

**Comment by thesteve0** [comment]
Hey Jeff:
Thanks for reporting but I actually have no control over that part. Can you please take the report and send it to openshift@redhat.com. Please send along the app full url, the UUID, and let them know they have permission to go in to troubleshoot. I think I saw something similar with my app so I will chime in to the email chain. They will probably want one of us to file a bugzilla report, but let's wait until they troubleshoot some.

Again thanks for taking the time to help!
Steve
